name: 'Push to main'

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install testing dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
      - name: Check with flake8
        run: |
          flake8 . --ignore=E501
      - name: Reboot API
        uses: fifsky/ssh-action@master
        with:
          command: |
            ./yanbf-reboot.sh
            exit
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
